export const JokesReply: string[] = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't programmers like nature? It has too many bugs.",
    "Why do Java developers wear glasses? Because they don't see sharp.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the math book look sad? Because it had too many problems.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the coffee file a police report? It got mugged!",
    "Why did the cookie go to the doctor? Because it felt crummy!",
    "Why did the computer go to the doctor? It had a virus!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why did the math teacher break up with the calculator? It was too divisive.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "Why did the picture go to jail? Because it was framed.",
    "Why did the computer catch a cold? It left its Windows open.",
    "Why was the stadium so cool? It was full of fans.",
    "Why did the belt get arrested? For holding up a pair of pants.",
    "Why did the music teacher go to jail? Too many sharp notes.",
    "Why don’t oysters donate to charity? Because they’re shellfish.",
    "Why did the programmer quit his job? Because he didn’t get arrays.",
    "Why did the clock get kicked out of class? It was ticking too much.",
    "Why did the cow win an award? Outstanding in its field.",
    "Why did the banana go to the doctor? It wasn’t peeling well.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "Why did the computer go to therapy? Too many unresolved issues.",
    "Why did the pencil break up with the eraser? Too many mistakes.",
    "Why was six afraid of seven? Because seven eight nine.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "Why don’t programmers trust stairs? They’re always up to something.",
    "Why did the book join the police? It wanted to go undercover.",
    "Why did the orange stop rolling? It ran out of juice.",
    "Why did the keyboard go to school? To improve its typing skills.",
    "Why did the dog sit in the shade? Because it didn’t want to be a hot dog.",
    "Why did the calendar break up with January? Too many dates.",
    "Why did the phone need glasses? It lost its contacts.",
    "Why did the fish blush? It saw the ocean’s bottom.",
    "Why did the light bulb fail school? It wasn’t too bright.",
    "Why did the computer cross the road? To get to the other site.",
    "Why did the banker switch careers? He lost interest.",
    "Why did the snowman call a cab? It was melting down.",
    "Why did the broom get promoted? It swept the competition.",
    "Why did the grape stop in the middle of the road? It ran out of juice.",
    "Why did the calculator stay home? It needed to recharge.",
    "Why did the shirt go to jail? It was caught laundering money.",
    "Why did the doctor carry a red pen? In case he needed to draw blood.",
    "Why did the Wi-Fi break up with the router? No connection.",
    "Why did the elevator feel awkward? It was going through ups and downs.",
    "Why did the teacher wear sunglasses? Because her students were so bright.",
    "Why did the astronaut break up with his girlfriend? He needed space.",
    "Why did the computer hate dating? Too many bad connections.",
    "Why did the sandwich go to the gym? To get better buns.",
    "Why did the mushroom get invited to every party? Because he was a fun-gi.",
    "Why did the cat sit on the computer? To keep an eye on the mouse.",
    "Why did the paper get promoted? It was tear-rific.",
    "Why did the robot go on vacation? To recharge its batteries.",
    "Why did the traffic light turn red? You’d be embarrassed too if you had to change in public.",
    "Why did the joke get a standing ovation? It really delivered."
]